---
title: gosh*
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@example.com
description: 'Hand-crafted cocktail bar

'
baseurl: "/gosh"
url: ''
markdown: kramdown
sass:
  sass_dir: assets/css/_sass
  style: compressed
plugins:
- jekyll-polyglot
languages:
- en
- am
- it
- de
default_lang: en
exclude_from_localization:
- assets
